### ISSUE TITLE
Get Zoom Room Locations.

### ISSUE THREAD

**Issue by DamagedDingo** [JosephMcEvoy/PSZoom#20]
I'm not sure what a good solution is to this but I need to get the hierarchy for a given room. 

Zoom provides this API that get all locations with the parent location id so you can crawl up the chain or you can provide a parent ID and get just the one item returned. 

My solution is this..

```
$ZoomRoomLocations = Get-ZoomRoomLocations -page_size 300

function Get-SingleZoomRoomLocation {
    [CmdletBinding()]
    param (
        [String]$location_id,
        [Array]$Locations
    )
    
    begin {
        if ($Locations) {
            
        }
        Else{
            $Locations = Get-ZoomRoomLocations -PageSize 300
        }
    }
    
    process {

        $FloorObj =  $Locations | Where { $_.id -like $location_id}
        $CampusObj = $Locations | Where { $_.id -like $FloorObj.parent_location_id}
        $CityObj = $Locations | Where { $_.id -like $CampusObj.parent_location_id}
        $StateObj = $Locations | Where { $_.id -like $CityObj.parent_location_id}
        $CountryObj = $Locations | Where { $_.id -like $StateObj.parent_location_id}

        $hierarchy = @{
            Floor = $FloorObj.name
            Campus = $CampusObj.name
            City = $CityObj.name
            State = $StateObj.name
            Country = $CountryObj.name
        }

    }
    
    end {
        $hierarchy
    }
}
```

This uses Get-ZoomRoomLocations which is a normal API call, and then pass that into the function above to spit out the floor,campus,city,state,country for the given (room).location_id

I gave it a param to accept the input from Get-ZoomRoomLocations because this will be used in a loop to build a ZoomRoom Object that contains all information for a zoom room (concat of each function in PSZoom that will be passed to a CMDB for us.

I'm sure there is a better way of doing this to have it included as a function of your module but i don't know what that looks like. 

Unfortunately Get-ZoomRoomLocations only takes a parent_location_id so i can't include it else where as you need to start with a room ID and then you can crawl up the parent_location_id's to get the full list.

**Comment by AllElbows** [comment]
What that looks like as a script. 
https://pastebin.com/aRUyFJLY

**Comment by JosephMcEvoy** [comment]
Are these two API calls relevant to what you're trying to do?
https://marketplace.zoom.us/docs/api-reference/zoom-api/rooms-location/getzrlocationprofile
https://marketplace.zoom.us/docs/api-reference/zoom-api/rooms-location/getzrlocationstructure

**Comment by AllElbows** [comment]
Sort of.. the first one is providing a single location ID (floor) which is what I'm using to start the crawl upwards from, and the other returns the actual org structure (what would be seen in the portal to browse through). I guess that means that you could change them I.e change **floor** to **level** etc.. so that would have to be taken into consideration as well (which I didn't do above). Easy enough though, just do the second call (second link you provided) first and use the object returned for the names of structures ($structures[0] for country or whatever people called theirs etc)

I was unable to find anything to give full path/location in single request. 

I can handle this in the script of cause but I feel it should be in the module as it's an important piece of information for maintenance (at least for us and I assume anyone else with a lot of rooms)

In my script I use almost all the zoom room calls and put them in a single object so that I can pass it to our CMDB. Location allows me to assign the Room to a local support group and allows service desk to know where a room is located to route tickets..

I actually had plans to take a look again today to determine if a function should be added that doesn't directly match an API call from zoom. Something like Get-AllAvalibleZoomRoomInfo.
Again, it **can** be handled in the script but it sure would make people's lives easier to have it contained within this module, especially as my other module (Insight/CMDB) will use PSzoom as a example on how to build the Structure and import Assets and Business Services. 😁

**Comment by JosephMcEvoy** [comment]
I think there could be some limited exceptions for adding cmdlets that don't necessarily wrap existing Zoom API calls. Some cmdlets already go above and beyond, like get-zoomuser's '-all' switch which runs get-zoomuser recursively, making multiple API calls in one cmdlet. This isn't too different imo.

**Comment by AllElbows** [comment]
Ok that sound good. 
Let me see if I can wrap it up to something small and not too intensive and I'll push it to you for review because I'm not that efficient with my code so it will be functional but I'm sure will need to be simplified.

**Comment by DamagedDingo** [comment]
Do you want to check my fork?
I have added a few more functions and I have a script in Get-ZoomRoomsAggregated.ps1 (which will need to be turned in to a functions later).

My problem is that I need to pull info from multiple sources. Is it better to reference existing functions as I have in the script or to put a copy of the required functions inside this one?

Also, not sure what to do about using another module. I'm using Join-Object because its simple but maybe we will want to do that natively?

The output in $Obj is good, it contains everything that's required to get a actual overview of a zoom room.

**Comment by DamagedDingo** [comment]
Do you want to check my fork?
I have added a few more functions and I have a script in Get-ZoomRoomsAggregated.ps1 (which will need to be turned in to a functions later).

My problem is that I need to pull info from multiple sources. Is it better to reference existing functions as I have in the script or to put a copy of the required functions inside this one?

Also, not sure what to do about using another module. I'm using Join-Object because its simple but maybe we will want to do that natively?

The output in $Obj is good, it contains everything that's required to get a actual overview of a zoom room.

**Comment by JosephMcEvoy** [comment]
Hi,

Apologies for taking a bit to get back to you. 

It is best practice to not repeat yourself (DRY). So it would be best to reference other functions from other scripts. When referencing a function that isn't a PSZoom function (such as get-jwt), put it in the Private functions folder, then import it.

I don't want to have any other dependencies if it can be helped. Is there another way to not use Join-Object?

**Comment by JosephMcEvoy** [comment]
Also if you could use a pull request for this, it is easier to view code.
